# Generated by Django 5.0.7 on 2025-04-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('emergency_clause', models.TextField(default='In case of emergency, 10% of the total cost will be charged.')),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
            ],
        ),
    ]
